/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package umich.ms.batmass.gui.core.components.plots;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 * Base class for holding a plot panel, it's corresponding info panel
 * and a Dataset list.
 * @author Dmitry
 */
public class PlotComponent extends JPanel {
    private PlotPanel plotPanel;
    
    protected boolean doShowInfoPanel = true;
    protected boolean doShowDatasetPanel = true;

    /**
     * Creates new form PlotComponent
     */
    public PlotComponent() {
        initComponents();
        
        this.setLayout(new BorderLayout());
        this.plotPanel = new PlotPanel();
        this.add(plotPanel, BorderLayout.CENTER);
//        if (doShowInfoPanel)
//            this.add()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
