/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package umich.ms.batmass.gui.core.components.plots;

import java.util.List;
import javax.swing.JPanel;
import javax.swing.event.EventListenerList;

/**
 *
 * @author Dmitry
 */
public class PlotPanel extends JPanel {
    
    protected List<Dataset> datasets;
    private EventListenerList listeners = new EventListenerList();

    /**
     * Creates new form PlotPanel
     */
    public PlotPanel() {
        initComponents();
    }
    
    
    /**
     * Creates an info panel and subscribes it to events from this PlotPanel.
     * @return 
     */
    public PlotInfoPanel createInfoPanel() {
        PlotInfoPanel pip = new PlotInfoPanel();
        throw new UnsupportedOperationException("creatinon of info panel not implemented yet");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
