/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package umich.ms.batmass.gui.examples.actions;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;

/**
 * It is important to register actions not in Actions/CookieClass/SubMenu,
 * but in CookieClass/SubMenu - a .shadow file is automatically generated by
 * NetBeans in Actions/CookieClass/SubMenu then.
 * @author dmitriya
 */
//@ActionID(
//    category = "LCMSFileDesc/View",
//    id = "umich.ms.batmass.gui.lcmsfileactions.ViewChromatogramAction")
//@ActionRegistration(
//    displayName = "#CTL_ViewChromatogramAction",
//    iconBase = "umich/ms/batmass/gui/resources/view_chromatogram_16.png"
//)
//@ActionReference(
//    path = "BatMass/Actions/Files/Categories/" + NodeFactoryLCMSFiles.TYPE,
//    position=50)
//@Messages("CTL_ViewChromatogramAction=Chromatogram")
public class ViewChromatogramAction implements ActionListener {

    @Override
    public void actionPerformed(ActionEvent e) {
        
        String msg = "should launch chromatogram view";
        NotifyDescriptor d = new NotifyDescriptor.Message(msg, NotifyDescriptor.INFORMATION_MESSAGE);
        DialogDisplayer.getDefault().notify(d);
    }

}
